name: nadasie_mobile_app
description: A mobile app for NaDaSie WooCommerce store.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  shared_preferences: ^2.0.15
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png