name: Build Android APK

on:
  workflow_dispatch: # ręczne uruchamianie z Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install

      # Budowanie APK w profilu "preview"
      - name: Build APK
        run: eas build -p android --profile preview --non-interactive --local
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: nadasie-app
          path: build-*/outputs/**/*.apk
